-- precondition: user hron should exist, see hron.sql
alter session set current_schema = hron;

-- ensure using the english standard numeric separators
alter session set NLS_NUMERIC_CHARACTERS = '.,';

-- cleanup
begin
    drop_table_if_exists('car_service');
    drop_table_if_exists('service');
    drop_table_if_exists('car');
    drop_fk_if_exists('department', 'department_manager_fk');
    drop_table_if_exists('employee');
    drop_table_if_exists('department');
    drop_table_if_exists('location');
    drop_table_if_exists('country');
    drop_table_if_exists('region');
    drop_table_if_exists('job');

    drop_sequence_if_exists('car_seq');
end;
/

-- simple: "one" region, many countries
create table region (
	region_id integer generated by default on null as identity primary key,
	name varchar2(25)
);

insert into region (name) values ('Europe');
insert into region (name) values ('Americas');
insert into region (name) values ('Asia');
insert into region (name) values ('Middle East and Africa');
commit;

-- a "many" table with a natural PK, to one region
create table country (
	country_id char(2) primary key,
	name varchar2(40),
	region_id integer,

    constraint country_region_fk foreign key (region_id) references region (region_id)
);

declare
    v_europe region.region_id%type;
    v_americas region.region_id%type;
    v_asia region.region_id%type;
    v_mea region.region_id%type;
begin
    select region_id into v_europe from region where name = 'Europe';
    select region_id into v_americas from region where name = 'Americas';
    select region_id into v_asia from region where name = 'Asia';
    select region_id into v_mea from region where name = 'Middle East and Africa';
    
    insert into country (country_id, name, region_id) values ('AR', 'Argentina', v_americas);
    insert into country (country_id, name, region_id) values ('AU', 'Australia', v_asia);
    insert into country (country_id, name, region_id) values ('BE', 'Belgium', v_europe);
    insert into country (country_id, name, region_id) values ('BR', 'Brazil', v_americas);
    insert into country (country_id, name, region_id) values ('CA', 'Canada', v_americas);
    insert into country (country_id, name, region_id) values ('CH', 'Switzerland', v_europe);
    insert into country (country_id, name, region_id) values ('CN', 'China', v_asia);
    insert into country (country_id, name, region_id) values ('DE', 'Germany', v_europe);
    insert into country (country_id, name, region_id) values ('DK', 'Denmark', v_europe);
    insert into country (country_id, name, region_id) values ('EG', 'Egypt', v_mea);
    insert into country (country_id, name, region_id) values ('FR', 'France', v_europe);
    insert into country (country_id, name, region_id) values ('IL', 'Israel', v_mea);
    insert into country (country_id, name, region_id) values ('IN', 'India', v_asia);
    insert into country (country_id, name, region_id) values ('IT', 'Italy', v_europe);
    insert into country (country_id, name, region_id) values ('JP', 'Japan', v_asia);
    insert into country (country_id, name, region_id) values ('KW', 'Kuwait', v_mea);
    insert into country (country_id, name, region_id) values ('ML', 'Malaysia', v_asia);
    insert into country (country_id, name, region_id) values ('MX', 'Mexico', v_americas);
    insert into country (country_id, name, region_id) values ('NG', 'Nigeria', v_mea);
    insert into country (country_id, name, region_id) values ('NL', 'Netherlands', v_europe);
    insert into country (country_id, name, region_id) values ('SG', 'Singapore', v_asia);
    insert into country (country_id, name, region_id) values ('UK', 'United Kingdom', v_europe);
    insert into country (country_id, name, region_id) values ('US', 'United States of America', v_americas);
    insert into country (country_id, name, region_id) values ('ZM', 'Zambia', v_mea);
    insert into country (country_id, name, region_id) values ('ZW', 'Zimbabwe', v_mea);
    commit;
end;
/

-- "many" location in one country
create table location (
	location_id integer generated by default on null as identity start with 1000 increment by 100 primary key,
	street_address varchar2(40),
	postal_code varchar2(12),
	city varchar2(30) not null,
	state_province varchar2(25),
	country_id char(2),

    constraint location_country_fk foreign key (country_id) references country (country_id)
);

declare
    v_it country.country_id%type;
    v_jp country.country_id%type;
    v_us country.country_id%type;
    v_ca country.country_id%type;
    v_cn country.country_id%type;
    v_in country.country_id%type;
    v_au country.country_id%type;
    v_sg country.country_id%type;
    v_uk country.country_id%type;
    v_de country.country_id%type;
    v_br country.country_id%type;
    v_ch country.country_id%type;
    v_nl country.country_id%type;
    v_mx country.country_id%type;
begin
    select country_id into v_it from country where name = 'Italy';
    select country_id into v_jp from country where name = 'Japan';
    select country_id into v_us from country where name = 'United States of America';
    select country_id into v_ca from country where name = 'Canada';
    select country_id into v_cn from country where name = 'China';
    select country_id into v_in from country where name = 'India';
    select country_id into v_au from country where name = 'Australia';
    select country_id into v_sg from country where name = 'Singapore';
    select country_id into v_uk from country where name = 'United Kingdom';
    select country_id into v_de from country where name = 'Germany';
    select country_id into v_br from country where name = 'Brazil';
    select country_id into v_ch from country where name = 'Switzerland';
    select country_id into v_nl from country where name = 'Netherlands';
    select country_id into v_mx from country where name = 'Mexico';
    
    insert into location (street_address, postal_code, city, state_province, country_id) values
    	('Via Cola di Rienzo, 1297', '00989', 'Roma', 'RM', v_it);
    insert into location (street_address, postal_code, city, state_province, country_id) values
        ('Calle della Testa, 93091', '10934', 'Venice', 'VE', v_it);
    insert into location (street_address, postal_code, city, state_province, country_id) values
        ('2017 Shinjuku-ku', '1689', 'Tokyo', 'Tokyo Prefecture', v_jp);
    insert into location (street_address, postal_code, city, state_province, country_id) values
        ('9450 Kamiya-cho', '6823', 'Hiroshima', null, v_jp);
    insert into location (street_address, postal_code, city, state_province, country_id) values
        ('2014 Jabberwocky Rd', '26192', 'Southlake', 'Texas', v_us);
    insert into location (street_address, postal_code, city, state_province, country_id) values
        ('2011 Interiors Blvd', '99236', 'South San Francisco', 'California', v_us);
    insert into location (street_address, postal_code, city, state_province, country_id) values
        ('2007 Zagora St', '50090', 'South Brunswick', 'New Jersey', v_us);
    insert into location (street_address, postal_code, city, state_province, country_id) values
        ('2004 Charade Rd', '98199', 'Seattle', 'Washington', v_us);
    insert into location (street_address, postal_code, city, state_province, country_id) values
        ('147 Spadina Ave', 'M5V 2L7', 'Toronto', 'Ontario', v_ca);
    insert into location (street_address, postal_code, city, state_province, country_id) values
        ('6092 Boxwood St', 'YSW 9T2', 'Whitehorse', 'Yukon', v_ca);
    insert into location (street_address, postal_code, city, state_province, country_id) values
        ('40-5-12 Laogianggen', '190518', 'Beijing', null, v_cn);
    insert into location (street_address, postal_code, city, state_province, country_id) values
        ('1298 Vileparle (E)', '490231', 'Bombay', 'Maharashtra', v_in);
    insert into location (street_address, postal_code, city, state_province, country_id) values
        ('12-98 Victoria Street', '2901', 'Sydney', 'New South Wales', v_au);
    insert into location (street_address, postal_code, city, state_province, country_id) values
        ('198 Clementi North', '540198', 'Singapore', null, v_sg);
    insert into location (street_address, postal_code, city, state_province, country_id) values
        ('8204 Arthur St', null, 'London', null, v_uk);
    insert into location (street_address, postal_code, city, state_province, country_id) values
        ('Magdalen Centre, The Oxford Science Park', 'OX9 9ZB', 'Oxford', 'Oxford', v_uk);
    insert into location (street_address, postal_code, city, state_province, country_id) values
        ('9702 Chester Road', '09629850293', 'Stretford', 'Manchester', v_uk);
    insert into location (street_address, postal_code, city, state_province, country_id) values
        ('Schwanthalerstr. 7031', '80925', 'Munich', 'Bavaria', v_de);
    insert into location (street_address, postal_code, city, state_province, country_id) values
        ('Rua Frei Caneca 1360 ', '01307-002', 'Sao Paulo', 'Sao Paulo', v_br);
    insert into location (street_address, postal_code, city, state_province, country_id) values
        ('20 Rue des Corps-Saints', '1730', 'Geneva', 'Geneve', v_ch);
    insert into location (street_address, postal_code, city, state_province, country_id) values
        ('Murtenstrasse 921', '3095', 'Bern', 'BE', v_ch);
    insert into location (street_address, postal_code, city, state_province, country_id) values
        ('Pieter Breughelstraat 837', '3029SK', 'Utrecht', 'Utrecht', v_nl);
    insert into location (street_address, postal_code, city, state_province, country_id) values
        ('Mariano Escobedo 9991', '11932', 'Mexico City', 'Distrito Federal', v_mx);
    commit;    
end;
/

-- "one" job to many employees
create table job (
    job_id integer generated by default on null as identity primary key,
    title varchar2(35) not null,
    min_salary decimal(6,0),
    max_salary decimal(6,0),

    constraint job_salary_ck check (min_salary < max_salary)
);

insert into job (title, min_salary, max_salary) values ('President', 20080, 40000);
insert into job (title, min_salary, max_salary) values ('Vice President', 15000, 30000);
insert into job (title, min_salary, max_salary) values ('Assistant', 3000, 6000);
insert into job (title, min_salary, max_salary) values ('Finance Manager', 8200, 16000);
insert into job (title, min_salary, max_salary) values ('Accountant', 4200, 9000);
insert into job (title, min_salary, max_salary) values ('Accounting Manager', 8200, 16000);
insert into job (title, min_salary, max_salary) values ('Public Accountant', 4200, 9000);
insert into job (title, min_salary, max_salary) values ('Sales Manager', 10000, 20080);
insert into job (title, min_salary, max_salary) values ('Sales Representative', 6000, 12008);
insert into job (title, min_salary, max_salary) values ('Purchasing Manager', 8000, 15000);
insert into job (title, min_salary, max_salary) values ('Purchasing Clerk', 2500, 5500);
insert into job (title, min_salary, max_salary) values ('Stock Manager', 5500, 8500);
insert into job (title, min_salary, max_salary) values ('Stock Clerk', 2008, 5000);
insert into job (title, min_salary, max_salary) values ('Shipping Clerk', 2500, 5500);
insert into job (title, min_salary, max_salary) values ('Programmer', 4000, 10000);
insert into job (title, min_salary, max_salary) values ('Marketing Manager', 9000, 15000);
insert into job (title, min_salary, max_salary) values ('Marketing Representative', 4000, 9000);
insert into job (title, min_salary, max_salary) values ('Human Resources Representative', 4000, 9000);
insert into job (title, min_salary, max_salary) values ('Public Relations Representative', 4500, 10500);
commit;

-- a table with a complicated relation with employee, and "many" to one location
create table department(
	department_id integer generated by default on null as identity primary key,
	name varchar2(30) not null,
	manager_id integer unique,
	location_id integer,

    constraint department_location_fk foreign key (location_id) references location (location_id)
);

declare
    v_sewa location.location_id%type;
    v_sltx location.location_id%type;
    v_toon location.location_id%type;
    v_lond location.location_id%type;
    v_sfca location.location_id%type;
    v_muba location.location_id%type;
    v_oxfr location.location_id%type;
begin
    select location_id into v_sewa from location where city = 'Seattle';
    select location_id into v_sltx from location where city = 'Southlake';
    select location_id into v_toon from location where city = 'Toronto';
    select location_id into v_lond from location where city = 'London';
    select location_id into v_sfca from location where city = 'South San Francisco';
    select location_id into v_muba from location where city = 'Munich';
    select location_id into v_oxfr from location where city = 'Oxford';
    
    insert into department (name, location_id) values ('Administration', v_sewa);
    insert into department (name, location_id) values ('Marketing', v_toon);
    insert into department (name, location_id) values ('Purchasing', v_sewa);
    insert into department (name, location_id) values ('Human Resources', v_lond);
    insert into department (name, location_id) values ('Shipping', v_sfca);
    insert into department (name, location_id) values ('IT', v_sltx);
    insert into department (name, location_id) values ('Public Relations', v_muba);
    insert into department (name, location_id) values ('Sales', v_oxfr);
    insert into department (name, location_id) values ('Executive', v_sewa);
    insert into department (name, location_id) values ('Finance', v_sewa);
    insert into department (name, location_id) values ('Accounting', v_sewa);
    commit;
end;
/

-- other departements, not used
insert into department (name) values ('Treasury');
insert into department (name) values ('Benefits');
insert into department (name) values ('Manufacturing');
insert into department (name) values ('Contracting');
insert into department (name) values ('Operations');
insert into department (name) values ('IT Support');
insert into department (name) values ('IT Helpdesk');
insert into department (name) values ('Recruiting');
commit;

-- the core table, with many relations (also a self - manager)
create table employee(
	employee_id integer generated by default on null as identity start with 100 primary key,
	first_name varchar2(20),
	last_name varchar2(25) not null,
	phone integer unique not null,
	hired date not null,
	job_id integer not null,
	salary decimal(8,2),
	commission decimal(2,2),
	manager_id integer,
	department_id integer,

	constraint employee_salary_ck check (salary > 0),
    constraint employee_job_fk foreign key (job_id) references job (job_id),
    constraint employee_department_fk foreign key (department_id) references department (department_id)
);

declare
    v_pres job.job_id%type;
    v_vprs job.job_id%type;
    v_asst job.job_id%type;
    v_fimg job.job_id%type;
    v_prog job.job_id%type;
    v_acct job.job_id%type;
    v_pumg job.job_id%type;
    v_puck job.job_id%type;
    v_stmg job.job_id%type;
    v_stck job.job_id%type;
    v_samg job.job_id%type;
    v_sarp job.job_id%type;
    v_shck job.job_id%type;
    v_mkmg job.job_id%type;
    v_mkrp job.job_id%type;
    v_hrrp job.job_id%type;
    v_prrp job.job_id%type;
    v_acmg job.job_id%type;
    v_puac job.job_id%type;
begin
    select job_id into v_pres from job where title = 'President';
    select job_id into v_vprs from job where title = 'Vice President';
    select job_id into v_asst from job where title = 'Assistant';
    select job_id into v_fimg from job where title = 'Finance Manager';
    select job_id into v_prog from job where title = 'Programmer';
    select job_id into v_acct from job where title = 'Accountant';
    select job_id into v_pumg from job where title = 'Purchasing Manager';
    select job_id into v_puck from job where title = 'Purchasing Clerk';
    select job_id into v_stmg from job where title = 'Stock Manager';
    select job_id into v_stck from job where title = 'Stock Clerk';
    select job_id into v_samg from job where title = 'Sales Manager';
    select job_id into v_sarp from job where title = 'Sales Representative';
    select job_id into v_shck from job where title = 'Shipping Clerk';
    select job_id into v_mkmg from job where title = 'Marketing Manager';
    select job_id into v_mkrp from job where title = 'Marketing Representative';
    select job_id into v_hrrp from job where title = 'Human Resources Representative';
    select job_id into v_prrp from job where title = 'Public Relations Representative';
    select job_id into v_acmg from job where title = 'Accounting Manager';
    select job_id into v_puac from job where title = 'Public Accountant';

    -- employees with no commission
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Steven', 'King', 4511, date'2016-06-17', v_pres, 24000);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Neena', 'Kochhar', 4568, date'2014-09-21', v_vprs, 17000);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Lex', 'De Haan', 4518, date'2014-01-13', v_vprs, 17000);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Alexander', 'Hunold', 4567, date'2019-01-06', v_prog, 9000);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Bruce', 'Ernst', 4268, date'2021-05-21', v_prog, 6000);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('David', 'Austin', 4571, date'2018-06-25', v_prog, 4800);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Valli', 'Pataballa', 4560, date'2019-02-05', v_prog, 4800);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Diana', 'Lorentz', 5567, date'2020-02-07', v_prog, 4200);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Nancy', 'Greenberg', 4569, date'2015-08-17', v_fimg, 12008);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Daniel', 'Faviet', 4169, date'2015-08-16', v_acct, 9000);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('John', 'Chen', 4269, date'2018-09-28', v_acct, 8200);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Ismael', 'Sciarra', 4369, date'2018-09-05', v_acct, 7700);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Jose Manuel', 'Urman', 4469, date'2019-03-07', v_acct, 7800);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Luis', 'Popp', 4597, date'2020-12-07', v_acct, 6900);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Den', 'Raphaely', 4561, date'2020-12-02', v_pumg, 11000);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Alexander', 'Khoo', 4562, date'2021-05-03', v_puck, 3100);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Shelli', 'Baida', 4563, date'2018-12-24', v_puck, 2900);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Sigal', 'Tobias', 4564, date'2018-07-24', v_puck, 2800);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Guy', 'Himuro', 4565, date'2019-11-15', v_puck, 2600);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Karen', 'Colmenares', 4566, date'2021-08-07', v_puck, 2500);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Matthew', 'Weiss', 4330, date'2017-07-18', v_stmg, 8000);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Adam', 'Fripp', 2234, date'2018-04-10', v_stmg, 8200);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Payam', 'Kaufling', 3234, date'2016-05-01', v_stmg, 7900);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Shanta', 'Vollman', 4234, date'2018-10-10', v_stmg, 6500);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Kevin', 'Mourgos', 4244, date'2020-11-16', v_stmg, 5800);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Julia', 'Nayer', 4214, date'2018-07-16', v_stck, 3200);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Irene', 'Mikkilineni', 4224, date'2019-09-06', v_stck, 2700);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('James', 'Landry', 4334, date'2020-01-14', v_stck, 2400);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Steven', 'Markle', 4434, date'2021-03-08', v_stck, 2200);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Laura', 'Bissot', 5234, date'2018-08-20', v_stck, 3300);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Mozhe', 'Atkinson', 6234, date'2018-10-30',v_stck, 2800);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('James', 'Marlow', 7234, date'2018-02-16', v_stck, 2500);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('TJ', 'Olson', 8234, date'2020-04-10', v_stck, 2100);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Jason', 'Mallin', 1934, date'2017-06-14', v_stck, 3300);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Michael', 'Rogers', 4834, date'2019-08-26', v_stck, 2900);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Ki', 'Gee', 4734, date'2020-12-12', v_stck, 2400);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Hazel', 'Philtanker', 4634, date'2021-02-06', v_stck, 2200);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Renske', 'Ladwig', 4233, date'2016-07-14', v_stck, 3600);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Stephen', 'Stiles', 4034, date'2018-10-26', v_stck, 3200);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('John', 'Scantamburlo', 4019, date'2019-02-12', v_stck, 2700);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Joshua', 'Patel', 4824, date'2019-04-06', v_stck, 2500);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Trenna', 'Rajs', 4009, date'2016-10-17', v_stck, 3500);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Curtis', 'Davies', 4994, date'2018-01-29', v_stck, 3100);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Randall', 'Matos', 4874, date'2019-03-15', v_stck, 2600);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Peter', 'Vargas', 4004, date'2019-07-09', v_stck, 2500);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Winston', 'Taylor', 4276, date'2019-01-24', v_shck, 3200);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Jean', 'Fleaur', 4277, date'2019-02-23', v_shck, 3100);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Martha', 'Sullivan', 4878, date'2020-06-21', v_shck, 2500);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Girard', 'Geoni', 4879, date'2021-02-03', v_shck, 2800);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Nandita', 'Sarchand', 4816, date'2017-01-27', v_shck, 4200);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Alexis', 'Bull', 4846, date'2018-02-20', v_shck, 4100);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Juliet', 'Dullinger', 4256, date'2019-06-24', v_shck, 3400);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Anthony', 'Cabrio', 4271, date'2020-02-07', v_shck, 3000);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Kelly', 'Chung', 4376, date'2018-06-14', v_shck, 3800);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Jennifer', 'Dilly', 4872, date'2018-08-13', v_shck, 3600);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Tim', 'Gates', 4871, date'2019-07-11', v_shck, 2900);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Randall', 'Perkins', 4576, date'2020-12-19', v_shck, 2500);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Sarah', 'Bell', 4261, date'2017-02-04', v_shck, 4000);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Britney', 'Everett', 4226, date'2015-03-03', v_shck, 3900);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Samuel', 'McCain', 4218, date'2016-07-01', v_shck, 3200);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Vance', 'Jones', 4275, date'2017-03-17', v_shck, 2800);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Alana', 'Walsh', 4211, date'2019-04-24', v_shck, 3100);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Kevin', 'Feeney', 4222, date'2019-05-23', v_shck, 3000);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Donald', 'OConnell', 4231, date'2020-06-21', v_shck, 2600);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Douglas', 'Grant', 4240, date'2021-01-13', v_shck, 2600);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Jennifer', 'Whalen', 4241, date'2016-09-17', v_asst, 4400);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Michael', 'Hartstein', 4255, date'2017-02-17', v_mkmg, 13000);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Pat', 'Fay', 4259, date'2018-08-17', v_mkrp, 6000);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Susan', 'Mavris', 4215, date'2015-06-07', v_hrrp, 6500);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Hermann', 'Baer', 4288, date'2015-06-07', v_prrp, 10000);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Shelley', 'Higgins', 4280, date'2015-06-07', v_acmg, 12008);
    insert into employee (first_name, last_name, phone, hired, job_id, salary) values
        ('Willy', 'Gietz', 4281, date'2015-06-07', v_puac, 8300);
    
    -- sales have commission
    insert into employee (first_name, last_name, phone, hired, job_id, salary, commission) values
        ('John', 'Russell', 9200, date'2017-10-01', v_samg, 14000, 0.35);
    insert into employee (first_name, last_name, phone, hired, job_id, salary, commission) values
        ('Karen', 'Partners', 9261, date'2018-01-05', v_samg, 13500, 0.25);
    insert into employee (first_name, last_name, phone, hired, job_id, salary, commission) values
        ('Alberto', 'Errazuriz', 9218, date'2018-03-10', v_samg, 12000, 0.25);
    insert into employee (first_name, last_name, phone, hired, job_id, salary, commission) values
        ('Gerald', 'Cambrault', 9211, date'2020-10-15', v_samg, 11000, 0.25);
    insert into employee (first_name, last_name, phone, hired, job_id, salary, commission) values
        ('Eleni', 'Zlotkey', 9018, date'2018-01-29', v_samg, 10500, 0.15);
    insert into employee (first_name, last_name, phone, hired, job_id, salary, commission) values
        ('Peter', 'Tucker', 9299, date'2021-01-30', v_sarp, 10000, 0.25);
    insert into employee (first_name, last_name, phone, hired, job_id, salary, commission) values
        ('David', 'Bernstein', 5268, date'2018-03-24', v_sarp, 9500, 0.20);
    insert into employee (first_name, last_name, phone, hired, job_id, salary, commission) values
        ('Peter', 'Hall', 8968, date'2018-08-20', v_sarp, 9000, 0.20);
    insert into employee (first_name, last_name, phone, hired, job_id, salary, commission) values
        ('Christopher', 'Olsen', 9718, date'2019-03-30', v_sarp, 8000, 0.15);
    insert into employee (first_name, last_name, phone, hired, job_id, salary, commission) values
        ('Nanette', 'Cambrault', 9768, date'2019-12-09', v_sarp, 7500, 0.15);
    insert into employee (first_name, last_name, phone, hired, job_id, salary, commission) values
        ('Oliver', 'Tuvault', 9508, date'2020-11-23', v_sarp, 7000, 0.10);
    insert into employee (first_name, last_name, phone, hired, job_id, salary, commission) values
        ('Jane', 'King', 9228, date'2017-01-30', v_sarp, 10000, 0.30);
    insert into employee (first_name, last_name, phone, hired, job_id, salary, commission) values
        ('Patrick', 'Sully', 9252, date'2017-03-04', v_sarp, 9500, 0.30);
    insert into employee (first_name, last_name, phone, hired, job_id, salary, commission) values
        ('Allan', 'McEwen', 9222, date'2017-08-01', v_sarp, 9000, 0.30);
    insert into employee (first_name, last_name, phone, hired, job_id, salary, commission) values
        ('Lindsey', 'Smith', 9221, date'2018-03-10', v_sarp, 8000, 0.25);
    insert into employee (first_name, last_name, phone, hired, job_id, salary, commission) values
        ('Louise', 'Doran', 9225, date'2018-12-15', v_sarp, 7500, 0.25);
    insert into employee (first_name, last_name, phone, hired, job_id, salary, commission) values
        ('Sarath', 'Sewall', 9212, date'2019-11-03', v_sarp, 7000, 0.20);
    insert into employee (first_name, last_name, phone, hired, job_id, salary, commission) values
        ('Clara', 'Vishney', 9288, date'2018-11-11', v_sarp, 10500, 0.20);
    insert into employee (first_name, last_name, phone, hired, job_id, salary, commission) values
        ('Danielle', 'Greene', 9213, date'2020-03-19', v_sarp, 9500, 0.10);
    insert into employee (first_name, last_name, phone, hired, job_id, salary, commission) values
        ('Mattea', 'Marvins', 9256, date'2021-01-24', v_sarp, 7200, 0.05);
    insert into employee (first_name, last_name, phone, hired, job_id, salary, commission) values
        ('David', 'Lee', 9219, date'2021-02-23', v_sarp, 6800, 0.05);
    insert into employee (first_name, last_name, phone, hired, job_id, salary, commission) values
        ('Sundar', 'Ande', 9201, date'2021-03-24', v_sarp, 6400, 0.05);
    insert into employee (first_name, last_name, phone, hired, job_id, salary, commission) values
        ('Amit', 'Banda', 9208, date'2021-04-21', v_sarp, 6200, 0.05);
    insert into employee (first_name, last_name, phone, hired, job_id, salary, commission) values
        ('Lisa', 'Ozer', 9229, date'2018-03-11', v_sarp, 11500, 0.20);
    insert into employee (first_name, last_name, phone, hired, job_id, salary, commission) values
        ('Harrison', 'Bloom', 9286, date'2019-03-23', v_sarp, 10000, 0.15);
    insert into employee (first_name, last_name, phone, hired, job_id, salary, commission) values
        ('Tayler', 'Fox', 9298, date'2019-01-24', v_sarp, 9600, 0.15);
    insert into employee (first_name, last_name, phone, hired, job_id, salary, commission) values
        ('William', 'Smith', 9255, date'2020-02-23', v_sarp, 7400, 0.10);
    insert into employee (first_name, last_name, phone, hired, job_id, salary, commission) values
        ('Elizabeth', 'Bates', 9233, date'2020-03-24', v_sarp, 7300, 0.10);
    insert into employee (first_name, last_name, phone, hired, job_id, salary, commission) values
        ('Sundita', 'Kumar', 9268, date'2021-04-21', v_sarp, 6100, 0.05);
    insert into employee (first_name, last_name, phone, hired, job_id, salary, commission) values
        ('Ellen', 'Abel', 9267, date'2017-05-11', v_sarp, 11000, 0.25);
    insert into employee (first_name, last_name, phone, hired, job_id, salary, commission) values
        ('Alyssa', 'Hutton', 9266, date'2018-03-19', v_sarp, 8800, 0.20);
    insert into employee (first_name, last_name, phone, hired, job_id, salary, commission) values
        ('Jonathon', 'Taylor', 9265, date'2019-03-24', v_sarp, 8600, 0.15);
    insert into employee (first_name, last_name, phone, hired, job_id, salary, commission) values
        ('Jack', 'Livingston', 2926, date'2019-04-23', v_sarp, 8400, 0.15);
    insert into employee (first_name, last_name, phone, hired, job_id, salary, commission) values
        ('Kimberely', 'Grant', 9263, date'2020-05-24', v_sarp, 7000, 0.10);
    insert into employee (first_name, last_name, phone, hired, job_id, salary, commission) values
        ('Charles', 'Johnson', 9262, date'2021-01-04', v_sarp, 6200, 0.05);    
    commit;
end;
/

alter table department add constraint department_manager_fk foreign key (manager_id) references employee (employee_id);
alter table employee add constraint employee_manager_fk foreign key (manager_id) references employee (employee_id);

-- set the department FK
create or replace procedure set_department_fk_by_job(
	p_dep_name in department.name%type,
    p_job_title in job.title%type) is
begin
    update employee
    set department_id = ( select department_id from department where name =  p_dep_name )
    where job_id = ( select job_id from job where title = p_job_title );
end;
/

begin
    set_department_fk_by_job('Accounting', 'Public Accountant');
    set_department_fk_by_job('Accounting', 'Accounting Manager');

    set_department_fk_by_job('Administration', 'Assistant');

    set_department_fk_by_job('Executive', 'President');
    set_department_fk_by_job('Executive', 'Vice President');

    set_department_fk_by_job('Finance', 'Finance Manager');
    set_department_fk_by_job('Finance', 'Accountant');

    set_department_fk_by_job('Human Resources', 'Human Resources Representative');

    set_department_fk_by_job('IT', 'Programmer');

    set_department_fk_by_job('Marketing', 'Marketing Manager');
    set_department_fk_by_job('Marketing', 'Marketing Representative');

    set_department_fk_by_job('Public Relations', 'Public Relations Representative');

    set_department_fk_by_job('Purchasing', 'Purchasing Manager');
    set_department_fk_by_job('Purchasing', 'Purchasing Clerk');

    set_department_fk_by_job('Sales', 'Sales Manager');
    set_department_fk_by_job('Sales', 'Sales Representative');
    -- force Kim out of department
    update employee set department_id = null where first_name = 'Kimberely';
    
    set_department_fk_by_job('Shipping', 'Shipping Clerk');
    set_department_fk_by_job('Shipping', 'Stock Clerk');
    set_department_fk_by_job('Shipping', 'Stock Manager');
    commit;
end;
/

-- set the manager FK (self)
create or replace procedure set_manager_fk_by_job(
	p_mgr_fname in employee.first_name%type,
	p_mgr_lname in employee.last_name%type,
    p_job_title in job.title%type) is
begin
    update employee
    set manager_id = ( select employee_id from employee
        where first_name =  p_mgr_fname and last_name = p_mgr_lname )
    where job_id = ( select job_id from job where title = p_job_title );
end;
/

create or replace procedure set_manager_fk_by_name(
	p_mgr_fname in employee.first_name%type,
	p_mgr_lname in employee.last_name%type,
	p_fname in employee.first_name%type,
	p_lname in employee.last_name%type) is
begin
    update employee
    set manager_id = ( select employee_id from employee
        where first_name =  p_mgr_fname and last_name = p_mgr_lname )
    where first_name = p_fname and last_name = p_lname;
end;
/

begin
    set_manager_fk_by_job('Steven', 'King', 'Vice President');
    set_manager_fk_by_job('Steven', 'King', 'Purchasing Manager');
    set_manager_fk_by_job('Steven', 'King', 'Stock Manager');
    set_manager_fk_by_job('Steven', 'King', 'Sales Manager');
    set_manager_fk_by_job('Steven', 'King', 'Marketing Manager');
    
    set_manager_fk_by_name('Neena', 'Kochhar', 'Nancy', 'Greenberg');
    set_manager_fk_by_name('Neena', 'Kochhar', 'Shelley', 'Higgins');
    set_manager_fk_by_name('Neena', 'Kochhar', 'Jennifer', 'Whalen');
    set_manager_fk_by_name('Neena', 'Kochhar', 'Susan', 'Mavris');
    set_manager_fk_by_name('Neena', 'Kochhar', 'Hermann', 'Baer');

    set_manager_fk_by_job('Alexander', 'Hunold', 'Programmer');
    set_manager_fk_by_name('Lex', 'De Haan', 'Alexander', 'Hunold');

    set_manager_fk_by_job('Nancy', 'Greenberg', 'Accountant');
    set_manager_fk_by_job('Shelley', 'Higgins', 'Public Accountant');
    set_manager_fk_by_job('Michael', 'Hartstein', 'Marketing Representative');    
    set_manager_fk_by_job('Den', 'Raphaely', 'Purchasing Clerk');

    set_manager_fk_by_name('Matthew', 'Weiss', 'Julia', 'Nayer');
    set_manager_fk_by_name('Matthew', 'Weiss', 'Irene', 'Mikkilineni');
    set_manager_fk_by_name('Matthew', 'Weiss', 'James', 'Landry');
    set_manager_fk_by_name('Matthew', 'Weiss', 'Steven', 'Markle');
    set_manager_fk_by_name('Matthew', 'Weiss', 'Winston', 'Taylor');
    set_manager_fk_by_name('Matthew', 'Weiss', 'Jean', 'Fleaur');
    set_manager_fk_by_name('Matthew', 'Weiss', 'Martha', 'Sullivan');
    set_manager_fk_by_name('Matthew', 'Weiss', 'Girard', 'Geoni');

    set_manager_fk_by_name('Adam', 'Fripp', 'Laura', 'Bissot');
    set_manager_fk_by_name('Adam', 'Fripp', 'Mozhe', 'Atkinson');
    set_manager_fk_by_name('Adam', 'Fripp', 'James', 'Marlow');
    set_manager_fk_by_name('Adam', 'Fripp', 'TJ', 'Olson');
    set_manager_fk_by_name('Adam', 'Fripp', 'Nandita', 'Sarchand');
    set_manager_fk_by_name('Adam', 'Fripp', 'Alexis', 'Bull');
    set_manager_fk_by_name('Adam', 'Fripp', 'Juliet', 'Dullinger');
    set_manager_fk_by_name('Adam', 'Fripp', 'Anthony', 'Cabrio');

    set_manager_fk_by_name('Payam', 'Kaufling', 'Jason', 'Mallin');
    set_manager_fk_by_name('Payam', 'Kaufling', 'Michael', 'Rogers');
    set_manager_fk_by_name('Payam', 'Kaufling', 'Ki', 'Gee');
    set_manager_fk_by_name('Payam', 'Kaufling', 'Hazel', 'Philtanker');
    set_manager_fk_by_name('Payam', 'Kaufling', 'Kelly', 'Chung');
    set_manager_fk_by_name('Payam', 'Kaufling', 'Jennifer', 'Dilly');
    set_manager_fk_by_name('Payam', 'Kaufling', 'Tim', 'Gates');
    set_manager_fk_by_name('Payam', 'Kaufling', 'Randall', 'Perkins');

    set_manager_fk_by_name('Shanta', 'Vollman', 'Renske', 'Ladwig');
    set_manager_fk_by_name('Shanta', 'Vollman', 'Stephen', 'Stiles');
    set_manager_fk_by_name('Shanta', 'Vollman', 'John', 'Scantamburlo');
    set_manager_fk_by_name('Shanta', 'Vollman', 'Joshua', 'Patel');
    set_manager_fk_by_name('Shanta', 'Vollman', 'Sarah', 'Bell');
    set_manager_fk_by_name('Shanta', 'Vollman', 'Britney', 'Everett');
    set_manager_fk_by_name('Shanta', 'Vollman', 'Samuel', 'McCain');
    set_manager_fk_by_name('Shanta', 'Vollman', 'Vance', 'Jones');

    set_manager_fk_by_name('Kevin', 'Mourgos', 'Trenna', 'Rajs');
    set_manager_fk_by_name('Kevin', 'Mourgos', 'Curtis', 'Davies');
    set_manager_fk_by_name('Kevin', 'Mourgos', 'Randall', 'Matos');
    set_manager_fk_by_name('Kevin', 'Mourgos', 'Peter', 'Vargas');
    set_manager_fk_by_name('Kevin', 'Mourgos', 'Alana', 'Walsh');
    set_manager_fk_by_name('Kevin', 'Mourgos', 'Kevin', 'Feeney');
    set_manager_fk_by_name('Kevin', 'Mourgos', 'Donald', 'OConnell');
    set_manager_fk_by_name('Kevin', 'Mourgos', 'Douglas', 'Grant');

    set_manager_fk_by_name('John', 'Russell', 'Peter', 'Tucker');
    set_manager_fk_by_name('John', 'Russell', 'David', 'Bernstein');
    set_manager_fk_by_name('John', 'Russell', 'Peter', 'Hall');
    set_manager_fk_by_name('John', 'Russell', 'Christopher', 'Olsen');
    set_manager_fk_by_name('John', 'Russell', 'Nanette', 'Cambrault');
    set_manager_fk_by_name('John', 'Russell', 'Oliver', 'Tuvault');

    set_manager_fk_by_name('Karen', 'Partners', 'Jane', 'King');
    set_manager_fk_by_name('Karen', 'Partners', 'Patrick', 'Sully');
    set_manager_fk_by_name('Karen', 'Partners', 'Allan', 'McEwen');
    set_manager_fk_by_name('Karen', 'Partners', 'Lindsey', 'Smith');
    set_manager_fk_by_name('Karen', 'Partners', 'Louise', 'Doran');
    set_manager_fk_by_name('Karen', 'Partners', 'Sarath', 'Sewall');

    set_manager_fk_by_name('Alberto', 'Errazuriz', 'Clara', 'Vishney');
    set_manager_fk_by_name('Alberto', 'Errazuriz', 'Danielle', 'Greene');
    set_manager_fk_by_name('Alberto', 'Errazuriz', 'Mattea', 'Marvins');
    set_manager_fk_by_name('Alberto', 'Errazuriz', 'David', 'Lee');
    set_manager_fk_by_name('Alberto', 'Errazuriz', 'Sundar', 'Ande');
    set_manager_fk_by_name('Alberto', 'Errazuriz', 'Amit', 'Banda');

    set_manager_fk_by_name('Gerald', 'Cambrault', 'Lisa', 'Ozer');
    set_manager_fk_by_name('Gerald', 'Cambrault', 'Harrison', 'Bloom');
    set_manager_fk_by_name('Gerald', 'Cambrault', 'Tayler', 'Fox');
    set_manager_fk_by_name('Gerald', 'Cambrault', 'William', 'Smith');
    set_manager_fk_by_name('Gerald', 'Cambrault', 'Elizabeth', 'Bates');
    set_manager_fk_by_name('Gerald', 'Cambrault', 'Sundita', 'Kumar');

    set_manager_fk_by_name('Eleni', 'Zlotkey', 'Ellen', 'Abel');
    set_manager_fk_by_name('Eleni', 'Zlotkey', 'Alyssa', 'Hutton');
    set_manager_fk_by_name('Eleni', 'Zlotkey', 'Jonathon', 'Taylor');
    set_manager_fk_by_name('Eleni', 'Zlotkey', 'Jack', 'Livingston');
    set_manager_fk_by_name('Eleni', 'Zlotkey', 'Kimberely', 'Grant');
    set_manager_fk_by_name('Eleni', 'Zlotkey', 'Charles', 'Johnson');

    commit;    
end;
/

-- set manager FK on department table
create or replace procedure set_department_manager(
	p_mgr_fname in employee.first_name%type,
	p_mgr_lname in employee.last_name%type,
	p_dep_name in department.name%type) is
begin
    update department
    set manager_id = (
        select employee_id
        from employee
        where first_name =  p_mgr_fname and last_name = p_mgr_lname )
    where name = p_dep_name;
end;
/

begin
    set_department_manager('Jennifer', 'Whalen', 'Administration');
    set_department_manager('Michael', 'Hartstein', 'Marketing');
    set_department_manager('Den', 'Raphaely', 'Purchasing');
    set_department_manager('Susan', 'Mavris', 'Human Resources');
    set_department_manager('Adam', 'Fripp', 'Shipping');
    set_department_manager('Alexander', 'Hunold', 'IT');
    set_department_manager('Hermann', 'Baer', 'Public Relations');
    set_department_manager('John', 'Russell', 'Sales');
    set_department_manager('Steven', 'King', 'Executive');
    set_department_manager('Nancy', 'Greenberg', 'Finance');
    set_department_manager('Shelley', 'Higgins', 'Accounting');
    commit;
end;
/

-- "one" car for one employee, "many" cars seviced by many services
create table car(
	car_id integer primary key,
	name varchar2(40) unique,
	employee_id integer unique,

    constraint car_employee_fk foreign key (employee_id) references employee (employee_id)
);

create sequence car_seq;

create or replace procedure insert_car(
	p_car_name in car.name%type,
	p_first_name in employee.first_name%type,
	p_last_name in employee.last_name%type)
as
    v_employee_id int;
begin
    select employee_id into v_employee_id
    from employee
    where first_name = p_first_name and last_name = p_last_name;

    insert into car (car_id, name, employee_id) values
        (car_seq.nextval, p_car_name, v_employee_id);
end;
/

begin
    insert_car('Silver Hornet', 'Jennifer', 'Whalen');
    insert_car('White Phantom', 'Michael', 'Hartstein');
    insert_car('Batmobile', 'Den', 'Raphaely');
    insert_car('Starsky', 'Susan', 'Mavris');
    insert_car('Smurf', 'Adam', 'Fripp');
    insert_car('Fireball', 'Alexander', 'Hunold');
    insert_car('Poison', 'Neena', 'Kochhar');
    insert_car('Katana', 'Lex', 'De Haan');
    insert_car('Titanic', 'Hermann', 'Baer');
    insert_car('Dracula', 'John', 'Russell');
    insert_car('Zeppelin', 'Steven', 'King');
    insert_car('Ruby', 'Nancy', 'Greenberg');
    insert_car('Tortoise', 'Shelley', 'Higgins');
    commit;
end;
/

create or replace procedure get_employee_car(
	p_employee_id in employee.employee_id%type,
    p_car_name out car.name%type
) as
begin
	select name
	into p_car_name
	from car
	where employee_id = p_employee_id;
end;
/

create or replace procedure get_employee_salary(
    p_employee_id in employee.employee_id%type,
    p_salary out employee.salary%type) is
begin
    select salary
    into p_salary
    from employee
    where employee_id = p_employee_id;
end;
/

-- "many" services taking cares of many cars, many services could share one location
create table service(
	service_id integer generated by default on null as identity primary key,
	name varchar2(40),
	location_id integer,

	constraint service_location_fk foreign key (location_id) references location (location_id)
);

insert into service (name, location_id) values ('Inspired Glass', 1000);
insert into service (name, location_id) values ('Faith Auto Repair', 1000);
insert into service (name, location_id) values ('Happy Brake', 2300);
commit;

-- many to many with details
create table car_service(
	car_id integer,
	service_id integer,
	checkin timestamp,
	checkout timestamp,

	constraint car_service_time_ck check (checkin < checkout),
	primary key (car_id, service_id, checkin),
	constraint car_service_car_fk foreign key (car_id) references car (car_id),
	constraint car_service_service_fk foreign key (service_id) references service (service_id)
);

insert into car_service (car_id, service_id, checkin, checkout) values
	(1, 1, timestamp'2021-08-01 15:00:00', timestamp'2021-08-01 16:00:00');
insert into car_service (car_id, service_id, checkin, checkout) values
	(5, 2, timestamp'2021-08-03 14:00:00', timestamp'2021-08-03 19:00:00');
insert into car_service (car_id, service_id, checkin, checkout) values
	(1, 2, timestamp'2021-08-04 08:00:00', timestamp'2021-08-04 20:00:00');
insert into car_service (car_id, service_id, checkin, checkout) values
	(1, 3, timestamp'2021-10-12 15:00:00', timestamp'2021-10-12 18:00:00');
commit;
